export const urlBase = '/assets/img/'

export const watchImages = [
    {
      brand: 'jaguar',
      src: 'j1011_2.jpg',
      description: 'Jaguar',
      model: 'Modelo: J1011',
      id: 1,
    },
    {
      brand: 'jaguar',
      src: 'j671_a.jpg',
      description: 'Jaguar',
      model: 'Modelo: J671',
      id: 2,
    },
    {
      brand: 'jaguar',
      src: 'j688_1.jpg',
      description: 'Jaguar',
      model: 'Modelo: J688',
      id: 3,
    },
    {
      brand: 'jaguar',
      src: 'j964_3.jpg',
      description: 'Jaguar',
      model: 'Modelo: J964',
      id: 4,
    },
    {
      brand: 'jaguar',
      src: 'j988_1.jpg',
      description: 'Jaguar',
      model: 'Modelo: J988',
      id: 5,
    },
    {
      brand: 'jaguar',
      src: 'j860_D.jpg',
      description: 'Jaguar',
      model: 'Modelo: J860D',
      id: 6,
    },
    {
      brand: 'jaguar',
      src: 'j968_3.jpg',
      description: 'Jaguar',
      model: 'Modelo: J968_3',
      id: 7,
    },
    {
      brand: 'jaguar',
      src: 'j968_4.jpg',
      description: 'Jaguar',
      model: 'Modelo: J968_4',
      id: 8,
    },
    {
      brand: 'jaguar',
      src: 'j969_3.jpg',
      description: 'Jaguar',
      model: 'Modelo: J969',
      id: 9,
    },
    {
      brand: 'jaguar',
      src: 'j1010_1.jpg',
      description: 'Jaguar',
      model: 'Modelo: J1010',
      id: 10,
    },
    {
      brand: 'orient',
      src: '146-FQC0N002W0_1132016.jpg',
      description: 'Orient Start',
      model: 'Modelo: 146',
      id: 11,
    },
    {
      brand: 'orient',
      src: '147-FAC00005W0_2462016.jpg',
      description: 'Orient Start',
      model: 'Modelo: 147',
      id: 12,
    },
    {
      brand: 'orient',
      src: '147-RE-AU0005L00B.jpg',
      description: 'Orient Start',
      model: 'Modelo: 147 RE',
      id: 13,
    },
    {
      brand: 'orient',
      src: 'orient-tag00004d0.jpg',
      description: 'Orient Start',
      model: 'Modelo: Tag 4',
      id: 14,
    },
    {
      brand: 'orient',
      src: 'ra-aa0914e.jpg',
      description: 'Orient Start',
      model: 'Modelo: AR 0914',
      id: 15,
    },
    {
      brand: 'orient',
      src: 'ra-ar0202e.jpg',
      description: 'Orient Start',
      model: 'Modelo: AR 0202',
      id: 16,
    },
    {
      brand: 'orient',
      src: 're-au0306l-1.jpg',
      description: 'Orient Start',
      model: 'Modelo: RE 0306',
      id: 17,
    },
    {
      brand: 'orient',
      src: 'reloj-orient-star-re-at0015l00b-edicion-limitada.jpg',
      description: 'Orient Start',
      model: 'Modelo: RE 0015 E.D',
      id: 18,
    },
    {
      brand: 'orient',
      src: 's-l1600.jpg',
      description: 'Orient Start',
      model: 'Modelo: L1600',
      id: 19,
    },
    {
      brand: 'seiko',
      src: 'SFJ005P1.jpg',
      description: 'Seiko',
      model: 'Modelo: SFJ005P',
      id: 20,
    },
    {
      brand: 'seiko',
      src: 'SPB083J1.png',
      description: 'Seiko',
      model: 'Modelo: SPB083J1',
      id: 21,
    },
    {
      brand: 'seiko',
      src: 'SPB219J1.jpg',
      description: 'Seiko',
      model: 'Modelo: SPB219J1',
      id: 22,
    },
    {
      brand: 'seiko',
      src: 'SPB227J1.webp',
      description: 'Seiko',
      model: 'Modelo: SPB227J1',
      id: 23,
    },
    {
      brand: 'seiko',
      src: 'SRPE99K1.jpg',
      description: 'Seiko',
      model: 'Modelo: SRPE99K1',
      id: 24,
    },
    {
      brand: 'seiko',
      src: 'SRPF03K1.jpg',
      description: 'Seiko',
      model: 'Modelo: SRPF03K1',
      id: 25,
    },
    {
      brand: 'seiko',
      src: 'SRPG05J1.jpg',
      description: 'Seiko',
      model: 'Modelo: SRPG05J1',
      id: 26,
    },
    {
      brand: 'seiko',
      src: 'SRPG18K1.jpg',
      description: 'Seiko',
      model: 'Modelo: SRPG18K1',
      id: 27,
    },
    {
      brand: 'seiko',
      src: 'SSA343J1.jpg',
      description: 'Seiko',
      model: 'Modelo: SSA343J1',
      id: 28,
    },
    {
      brand: 'seiko',
      src: 'SSC917P1.jpg',
      description: 'Seiko',
      model: 'Modelo: SSC917P1',
      id: 29,
    },
    {
      brand: 'victorinox',
      src: '241685.jpg',
      description: 'Victorinox',
      model: 'Modelo: 241685',
      id: 30,
    },
    {
      brand: 'victorinox',
      src: '241710.jpg',
      description: 'Victorinox',
      model: 'Modelo: 241710',
      id: 31,
    },
    {
      brand: 'victorinox',
      src: '241854.jpg',
      description: 'Victorinox',
      model: 'Modelo: 241854',
      id: 32,
    },
    {
      brand: 'victorinox',
      src: '241866.jpg',
      description: 'Victorinox',
      model: 'Modelo: 241866',
      id: 33,
    },
    {
      brand: 'victorinox',
      src: '241921.jpg',
      description: 'Victorinox',
      model: 'Modelo: 241921',
      id: 34,
    },
    {
      brand: 'victorinox',
      src: '241975.jpg',
      description: 'Victorinox',
      model: 'Modelo: 241975',
      id: 35,
    },
    {
      brand: 'victorinox',
      src: '241982.jpg',
      description: 'Victorinox',
      model: 'Modelo: 241982',
      id: 36,
    },
    {
      brand: 'victorinox',
      src: '242009.jpg',
      description: 'Victorinox',
      model: 'Modelo: 242009',
      id: 37,
    },
    {
      brand: 'victorinox',
      src: '249174.jpg',
      description: 'Victorinox',
      model: 'Modelo: 249174',
      id: 38,
    },
    {
      brand: 'victorinox',
      src: 'victorinox-dive-pro-v241991.jpg',
      description: 'Victorinox',
      model: 'Modelo: V241991',
      id: 39,
    },
  ];
  